version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: taxi-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: taxi-app
    volumes:
      - mongodb_data:/data/db
    networks:
      - taxi-network

  redis:
    image: redis:7-alpine
    container_name: taxi-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - taxi-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: taxi-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/taxi-app?authSource=admin
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-super-secret-jwt-key-here
      - PORT=5000
    depends_on:
      - mongodb
      - redis
    networks:
      - taxi-network

volumes:
  mongodb_data:

networks:
  taxi-network:
    driver: bridge
